### ISSUE TITLE
[Severe] Not possible to add images

### ISSUE THREAD

**Issue by le-dawg** [Gomah/bluise#11]
I have copied the same way that the logo images is loaded.

1. Upload image using NetlifzCMS backend.
2. add a new line in the `app/content/settings/general.json` adding an image: `"testimg": "/images/uploads/testimg.png",`
3. Add this in the index.vue 
```
<img
          alt="Hero"
          class="rounded shadow-xl"
          src="testimg"
        />
```

And it doesn't render. The LOGO works the same way, except that it is wrapped in in a link. Pls fix.

**Comment by ykhli** [comment]
@le-dawg  the fix is here https://github.com/Gomah/bluise/pull/16
