### ISSUE TITLE
page transitions 

### ISSUE THREAD

**Issue by dialformonkey** [Gomah/bluise#4]
accidental issue

**Comment by dialformonkey** [comment]
missing nuxt.jsconfig mode: 'universal',

**Comment by bunnydreams** [comment]
@dialformonkey Did you have the situation where the page transitions don't show up on deployment? If yes, what did you do to fix it?

**Comment by bunnydreams** [comment]
If anyone has any problems with not seeing page transitions, replace `whitelist` with `whitelistPatterns` in nuxt.config.ts.

**Comment by Gomah** [comment]
Thanks @bunnydreams for the fix!

I'll update the boilerplate soon, it will remove `purgeCSS` from `@nuxtjs/tailwindcss`

**Comment by Gomah** [comment]
727baa2c4ba36de8a30d5bb4561627a16c6e62e0 should fix it
