### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by patrickxchong** [Gomah/bluise#6]
The repo README mentions that it implements pagination, but I don't see it in the code. Is it something that you plan to add in the future?

**Comment by Gomah** [comment]
That's right, I actually forgot to add it, got confused with another project, sorry!

Just added the logic in the [feat/pagination branch](https://github.com/Gomah/bluise/tree/feat/pagination), I'll add the `Pagination` component later on 😄

**Comment by bunnydreams** [comment]
Alright! Looking forward to it 😄

**Comment by Gomah** [comment]
Done in 727baa2c4ba36de8a30d5bb4561627a16c6e62e0
